<a href="https://colab.research.google.com/github/Anusha-Chittiraju123/NASSCOM/blob/main/WEEK%203/Loading_Datasets_from_Multiple_Sources.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import kagglehub

path = kagglehub.dataset_download("heptapod/titanic")

print("Dataset downloaded to:", path)

Using Colab cache for faster access to the 'titanic' dataset.
Dataset downloaded to: /kaggle/input/titanic

In [23]:
df = pd.read_csv(path + "/train_and_test2.csv")
df.head()

,Passengerid,Age,Fare,Sex,sibsp,zero,zero.1,zero.2,zero.3,zero.4,zero.5,zero.6,Parch,zero.7,zero.8,zero.9,zero.10,zero.11,zero.12,zero.13,zero.14,Pclass,zero.15,zero.16,Embarked,zero.17,zero.18,2urvived
0,1,22.0,7.2500,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,2.0,0,0,0
1,2,38.0,71.2833,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0.0,0,0,1
2,3,26.0,7.9250,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,2.0,0,0,1
3,4,35.0,53.1000,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,2.0,0,0,1
4,5,35.0,8.0500,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,3,0,0,2.0,0,0,0

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [26]:
import requests
import pandas as pd

url = "https://api.exchangerate-api.com/v4/latest/USD"

response = requests.get(url)
data = response.json()

rates = data["rates"]

df = pd.DataFrame(list(rates.items()), columns=["Currency","Rate"])
df.head()

  Currency    Rate
0      USD    1.00
1      AED    3.67
2      AFN   64.55
3      ALL   80.11
4      AMD  363.18

In [27]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("bank.db")

data = {
    "Customer_ID":[1,2,3,4],
    "Loan_Amount":[200000,150000,300000,180000],
    "Credit_Score":[720,680,650,700]
}

df = pd.DataFrame(data)

df.to_sql("customers", conn, if_exists="replace", index=False)

4

In [28]:
query = "SELECT * FROM customers"

df = pd.read_sql(query, conn)
df.head()

   Customer_ID  Loan_Amount  Credit_Score
0            1       200000           720
1            2       150000           680
2            3       300000           650
3            4       180000           700